import { ContactFormType } from "@/app/types/email";

const nodemailer = require("nodemailer");

const transporter = nodemailer.createTransport({
  service: "gmail",
  host: "smtp.gmail.com",
  port: 465,
  secure: true, // Use `true` for port 465 and secure connection
  auth: {
    user: process.env.GMAIL_ID,
    pass: process.env.GMAIL_PASSWORD,
  },
});

export async function sendEmail(data: ContactFormType) {
  const { name, email, phone, message } = data;

  const emailContent = `
    <div style="font-family: Arial, sans-serif; color: #333;">
      <div style="padding: 20px; background-color: #f4f4f4; border-radius: 8px; max-width: 600px; margin: auto;">
        <h2 style="text-align: center; color: #6c63ff;">New Message from Salon24</h2>
        <p style="font-size: 16px;">You have received a new message from the contact form on your website.</p>
        <hr style="border-top: 1px solid #ddd;"/>
        <table style="width: 100%; font-size: 16px;">
          <tr>
            <td style="font-weight: bold; padding: 8px 0;">Name:</td>
            <td style="padding: 8px 0;">${name}</td>
          </tr>
          <tr>
            <td style="font-weight: bold; padding: 8px 0;">Email:</td>
            <td style="padding: 8px 0;">${email}</td>
          </tr>
          <tr>
            <td style="font-weight: bold; padding: 8px 0;">Phone:</td>
            <td style="padding: 8px 0;">${phone}</td>
          </tr>
          <tr>
            <td style="font-weight: bold; padding: 8px 0;">Message:</td>
            <td style="padding: 8px 0;">${message}</td>
          </tr>
        </table>
        <hr style="border-top: 1px solid #ddd;"/>
        <p style="text-align: center; font-size: 14px; color: #999;">This email was generated by Salon24.com</p>
      </div>
    </div>
  `;

  try {
    const info = await transporter.sendMail({
      from: `"Salon24 " <${process.env.GMAIL_ID}>`, // sender address
      to: "lovedeep5.abh@gmail.com, salon24official@gmail.com", // list of receivers
      subject: "New Message Received - Salon24.com", // Subject line
      html: emailContent, // html body
    });

    return info;
  } catch (error) {
    return error;
  }
}
